apiVersion: v1
kind: ConfigMap
metadata:
  name: matomo-install-env
  namespace: {{.Values.namespace}}
data:
  MATOMO_FIRST_USER_NAME={{.Values.matomo.dashboard.firstuser.username}}
  MATOMO_FIRST_USER_EMAIL={{.Values.matomo.dashboard.firstuser.email}}
  MATOMO_DB_HOST={{.Values.db.hostname}}
  MATOMO_DB_NAME={{.Values.db.name}}
  {{ if .Values.db.prefix }}
  MATOMO_DB_PREFIX={{.Values.db.prefix}}
  {{ end }}
  MATOMO_DB_USERNAME={{.Values.db.username}}