---
{{- if .Values.matomo.cronJobs.scheduledTasks.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: matomo-jobs-scheduled-tasks
  namespace: {{.Values.namespace}}
  {{- template "matomo.labels" .Values.matomo.cronJobs.scheduledTasks.labels }}
spec:
  schedule: {{quote .Values.matomo.cronJobs.scheduledTasks.schedule}}
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 10
  jobTemplate:
    spec:
      activeDeadlineSeconds: {{.Values.matomo.cronJobs.scheduledTasks.activeDeadlineSeconds}}
      template:
        spec:
          initContainers:
          - name: matomo-init
            image: {{.Values.matomo.image}}
            imagePullPolicy: {{default "IfNotPresent" .Values.matomo.imagePullPolicy}}
            securityContext:
              runAsUser: {{.Values.matomo.runAsUser}}
              privileged: false
              allowPrivilegeEscalation: false
            envFrom:
            - configMapRef:
              name: matomo-install-env
            env:
            {{ $type := (printf "%T" .Values.matomo.dashboard.firstuser.password) }}
            {{- if eq $type "string" -}}
            - name: MATOMO_FIRST_USER_PASSWORD
              value: {{ .Values.matomo.dashboard.firstuser.password }}
            {{- else -}}
            - name: MATOMO_FIRST_USER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.matomo.dashboard.firstuser.password.secretKeyRef.name }}
                  key: {{ .Values.matomo.dashboard.firstuser.password.secretKeyRef.key }}
            {{- end }}
            - name: MATOMO_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.db.password.secretKeyRef.name }}
                  key: {{ .Values.db.password.secretKeyRef.key }}
            resources:
              requests:
                memory: {{ .Values.matomo.cronJobs.scheduledTasks.resources.requests.memory }}
                cpu: {{ .Values.matomo.cronJobs.scheduledTasks.resources.requests.cpu  }}
              limits:
                memory: {{ .Values.matomo.cronJobs.scheduledTasks.resources.limits.memory }}
                cpu: {{ .Values.matomo.cronJobs.scheduledTasks.resources.limits.cpu }}
            command: [ 'sh' , '-c' , 'rsync -crlOt --no-owner --no-group --no-perms /usr/src/matomo/ /var/www/html/ && {{.Values.matomo.installCommand}}' ]
            volumeMounts:
              - name: static-data
                mountPath: /var/www/html
              - name: matomo-configuration
                mountPath: /tmp/matomo/
                readOnly: true
          containers:
          - name: matomo-jobs-scheduledtasks
            image: {{.Values.matomo.image}}
            imagePullPolicy: {{default "IfNotPresent" .Values.matomo.imagePullPolicy}}
            securityContext:
              runAsUser: {{.Values.matomo.runAsUser}}
              privileged: false
              allowPrivilegeEscalation: false
            command: [ 'sh' , '-c' , {{quote .Values.matomo.cronJobs.scheduledTasks.command}} ]
            env:
            - name: MARIADB_MATOMO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.db.password.secretKeyRef.name }}
                  key: {{ .Values.db.password.secretKeyRef.key }}
            resources:
              requests:
                memory: {{ .Values.matomo.cronJobs.scheduledTasks.resources.requests.memory }}
                cpu: {{ .Values.matomo.cronJobs.scheduledTasks.resources.requests.cpu  }}
              limits:
                memory: {{ .Values.matomo.cronJobs.scheduledTasks.resources.limits.memory }}
                cpu: {{ .Values.matomo.cronJobs.scheduledTasks.resources.limits.cpu }}
            volumeMounts:
              - name: static-data
                mountPath: /var/www/html
          restartPolicy: OnFailure
          {{- if .Values.matomo.imagePullSecrets }}
          imagePullSecrets:
            {{ toYaml .Values.matomo.imagePullSecrets }}
          {{- end }}
          volumes:
          - name: matomo-configuration
            configMap:
              name: matomo-configuration
          - name: static-data
            emptyDir: {}
{{- end -}}
