---
{{- if .Values.matomo.queuedTrackingMonitor.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: matomo-queuedtracking-monitor
  namespace: {{.Values.namespace}}
  labels:
    app: matomo-queuedtracking-monitor
spec:
  replicas: {{.Values.matomo.queuedTrackingMonitor.replicas | default 1}}
  selector:
    matchLabels:
      app: matomo-queuedtracking-monitor
  template:
    metadata:
      labels:
        app: matomo-queuedtracking-monitor
      annotations:
        kubernetes.io/change-cause: {{.Values.changeCause}}
    spec:
      initContainers:
      - name: matomo-init
        image: {{.Values.matomo.image}}
        securityContext:
          runAsUser: {{.Values.matomo.runAsUser}}
          privileged: false
          allowPrivilegeEscalation: false
        imagePullPolicy: {{default "IfNotPresent" .Values.matomo.imagePullPolicy}}
        envFrom:
        - configMapRef:
            name: matomo-install-env
        env:
        {{ $type := (printf "%T" .Values.matomo.dashboard.firstuser.password) }}
        {{- if eq $type "string" -}}
        - name: MATOMO_FIRST_USER_PASSWORD
          value: {{ .Values.matomo.dashboard.firstuser.password }}
        {{- else -}}
        - name: MATOMO_FIRST_USER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.matomo.dashboard.firstuser.password.secretKeyRef.name }}
              key: {{ .Values.matomo.dashboard.firstuser.password.secretKeyRef.key }}
        {{- end }}
        - name: MATOMO_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.db.password.secretKeyRef.name }}
              key: {{ .Values.db.password.secretKeyRef.key }}
        command: [ 'sh' , '-c' , 'rsync -crlOt --no-owner --no-group --no-perms /usr/src/matomo/ /var/www/html/ && {{.Values.matomo.installCommand}}' ]
        volumeMounts:
          - name: static-data
            mountPath: /var/www/html
          - name: matomo-configuration
            mountPath: /tmp/matomo/
            readOnly: true
      containers:
      - name: matomo
        image: {{.Values.matomo.image}}
        {{- if .Values.matomo.queuedTrackingMonitor.resources }}
        resources:
{{ toYaml .Values.matomo.queuedTrackingMonitor.resources | indent 10 }}
        {{- end }}
        securityContext:
          runAsUser: {{.Values.matomo.runAsUser}}
          privileged: false
          allowPrivilegeEscalation: false
        imagePullPolicy: {{default "IfNotPresent" .Values.matomo.imagePullPolicy}}
        env:
        - name: MATOMO_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.db.password.secretKeyRef.name }}
              key: {{ .Values.db.password.secretKeyRef.key }}
        command: [ 'sh' , '-c' , 'supervisord -n' ]
        volumeMounts:
          - name: static-data
            mountPath: /var/www/html
          - name: matomo-supervisor-queuedtrackingmonitor
            mountPath: /etc/supervisor/conf.d
            readOnly: true
      {{- if .Values.matomo.imagePullSecrets }}
      imagePullSecrets:
        {{ toYaml .Values.matomo.imagePullSecrets }}
      {{- end }}
      {{- if .Values.matomo.queuedTrackingMonitor.nodeSelector }}
      nodeSelector:
        {{ toYaml .Values.matomo.queuedTrackingMonitor.nodeSelector }}
      {{- end }}
      volumes:
      - name: matomo-configuration
        configMap:
          name: matomo-configuration
      - name: static-data
        emptyDir: {}
      - name: matomo-supervisor-queuedtrackingmonitor
        configMap:
          name: matomo-supervisor-queuedtrackingmonitor
{{- end -}}
